In [1]:
import numpy as np

# 1. Definir la Matriz A (2x3) - 2 filas, 3 columnas
# Datos de 2 muestras con 3 características (ej. Temperatura, Presión, Vibración)
A = np.array([
    [10.0, 5.0, 2.0],
    [12.0, 6.0, 3.0]
])
print("--- Matriz A (Datos de Entrada) ---")
print(A)
print("Dimensión (Filas, Columnas):", A.shape)
print("-" * 30)

# 2. Definir la Matriz B (3x1) - 3 filas, 1 columna
# Pesos de la red neuronal para esas 3 características
B = np.array([
    [0.5],
    [0.2],
    [0.1]
])
print("--- Matriz B (Pesos de la Red) ---")
print(B)
print("Dimensión (Filas, Columnas):", B.shape)
print("-" * 30)


# 3. Multiplicación Matricial (Dot Product)
# ¡CRUCIAL!: Para que la multiplicación A * B sea válida, el número de columnas de A (3)
# debe ser igual al número de filas de B (3).
# La matriz resultante será de 2x1.
C = np.dot(A, B) 

print("--- Matriz Resultado C = A · B (Multiplicación Matricial) ---")
print(C)
print("Dimensión de C:", C.shape)
print("-" * 30)

# 4. Cálculo de la Transpuesta (Importante para Backpropagation)
A_T = A.T # '.T' es el método de NumPy para obtener la transpuesta
print("--- Matriz Transpuesta de A (A.T) ---")
print(A_T)
print("Dimensión de A.T:", A_T.shape)

--- Matriz A (Datos de Entrada) ---
[[10.  5.  2.]
 [12.  6.  3.]]
Dimensión (Filas, Columnas): (2, 3)
------------------------------
--- Matriz B (Pesos de la Red) ---
[[0.5]
 [0.2]
 [0.1]]
Dimensión (Filas, Columnas): (3, 1)
------------------------------
--- Matriz Resultado C = A · B (Multiplicación Matricial) ---
[[6.2]
 [7.5]]
Dimensión de C: (2, 1)
------------------------------
--- Matriz Transpuesta de A (A.T) ---
[[10. 12.]
 [ 5.  6.]
 [ 2.  3.]]
Dimensión de A.T: (3, 2)
